export const CREDENTIALS = () => process.env.CREDENTIALS === 'true';
export const NODE_ENV = () => process.env.NODE_ENV;
export const PORT = () => process.env.PORT;
export const DB_HOST = () => process.env.DB_HOST;
export const DB_PORT = () => process.env.DB_PORT;
export const DB_USER = () => process.env.DB_USER;
export const DB_PASSWORD = () => process.env.DB_PASSWORD;
export const DB_DATABASE = () => process.env.DB_DATABASE;
export const SECRET_KEY = () => process.env.SECRET_KEY;
export const LOG_FORMAT = () => process.env.LOG_FORMAT;
export const LOG_DIR = () => process.env.LOG_DIR;
export const ORIGIN = () => process.env.ORIGIN;
export const EMAIL_USER = () => process.env.EMAIL_USER;
export const EMAIL_PASSWORD = () => process.env.EMAIL_PASSWORD;